# Generated by Django 3.2 on 2021-09-30 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('clientpatient', '0003_alter_client_client_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssessmentMaster',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Assessment Client')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityParamedic',
            fields=[
                ('community_paramedic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Community Paramedic')),
            ],
            options={
                'verbose_name': 'Community Paramedic',
                'verbose_name_plural': 'Community Paramedics',
            },
        ),
        migrations.CreateModel(
            name='HomeSafetyAssessmentQuestionGroup',
            fields=[
                ('question_group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_group_label', models.TextField()),
                ('question_group_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewClientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('assessment_master', models.ForeignKey(db_column='assessment_master', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.clientassessmentmaster', verbose_name='Client Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSafetyAssessmentQuestions',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('question_group', models.ForeignKey(db_column='question_group', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.homesafetyassessmentquestiongroup', verbose_name='Question Group')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSafetyAssessmentQuestionAnswers',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.BooleanField()),
                ('answer_detail', models.TextField(blank=True, null=True)),
                ('new_client_assessment', models.ForeignKey(db_column='new_client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newclientassessment', verbose_name='New Client Assessment Record')),
                ('question', models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.homesafetyassessmentquestions', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkLoad',
            fields=[
                ('daily_workload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('daily_workload_date', models.DateTimeField(blank=True, null=True)),
                ('client_caseload_casemanagement_number_clients', models.IntegerField(null=True)),
                ('client_caseload_casemanagement_total_time', models.TimeField()),
                ('client_caseload_regular_number_clients', models.IntegerField(null=True)),
                ('client_caseload_regular_total_time', models.TimeField()),
                ('community_paramedic', models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedic', verbose_name='Community Paramedic')),
            ],
        ),
        migrations.AddField(
            model_name='clientassessmentmaster',
            name='community_paramedic',
            field=models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedic', verbose_name='Community Paramedic'),
        ),
    ]
