# Generated by Django 3.2 on 2022-02-02 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('communityparamedic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityclientassessment',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='paramedic_clientassessment_client', to='authentication.applicationuser', verbose_name='Assessment Client'),
        ),
        migrations.AlterField(
            model_name='communityclientassessment',
            name='community_paramedic',
            field=models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, related_name='paramedic_clientassessment', to='authentication.applicationuser', verbose_name='Community Paramedic'),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='community_paramedic',
            field=models.ForeignKey(blank=True, db_column='community_paramedic', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paramedic_dailyworkload', to='authentication.applicationuser', verbose_name='Community Paramedic'),
        ),
        migrations.DeleteModel(
            name='CommunityParamedicUser',
        ),
    ]
