# Generated by Django 3.2 on 2021-10-05 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('communityparamedic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkload',
            name='daily_workload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommunityParamedicUser',
            fields=[
                ('community_paramedic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Community Paramedic')),
            ],
            options={
                'verbose_name': 'Community Paramedic',
                'verbose_name_plural': 'Community Paramedics',
            },
        ),
        migrations.AlterField(
            model_name='clientassessmentmaster',
            name='community_paramedic',
            field=models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedicuser', verbose_name='Community Paramedic'),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='community_paramedic',
            field=models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedicuser', verbose_name='Community Paramedic'),
        ),
        migrations.DeleteModel(
            name='CommunityParamedic',
        ),
    ]
