# Generated by Django 3.2 on 2021-10-05 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0002_auto_20211005_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityClientAssessment',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_status', models.CharField(blank=True, choices=[('EXISTING_CASE_MANAGEMENT_CLIENT', 'Existing Case Management Client'), ('NEW_CASE_MANAGEMENT_CLIENT', 'New Case Management Client')], default='NEW_CASE_MANAGEMENT_CLIENT', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingCaseClientAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCaseClientAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newclientassessment',
            name='assessment_master',
        ),
        migrations.AlterModelOptions(
            name='dailyworkload',
            options={'verbose_name': 'Daily Workload', 'verbose_name_plural': 'Daily Workloads'},
        ),
        migrations.RemoveField(
            model_name='homesafetyassessmentquestionanswers',
            name='new_client_assessment',
        ),
        migrations.DeleteModel(
            name='ClientAssessmentMaster',
        ),
    ]
