# Generated by Django 3.2 on 2021-10-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0003_auto_20211005_2334'),
        ('documents', '0009_auto_20211005_2334'),
        ('clientpatient', '0004_client_client_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewClientAssessment',
        ),
        migrations.AddField(
            model_name='communityclientassessment',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Assessment Client'),
        ),
        migrations.AddField(
            model_name='communityclientassessment',
            name='community_paramedic',
            field=models.ForeignKey(db_column='community_paramedic', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedicuser', verbose_name='Community Paramedic'),
        ),
        migrations.AddField(
            model_name='communityclientassessment',
            name='existing_case_client_assessment',
            field=models.ForeignKey(blank=True, db_column='existing_case_client_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.existingcaseclientassessment', verbose_name='Existing Case Client Assessment'),
        ),
        migrations.AddField(
            model_name='communityclientassessment',
            name='new_case_client_assessment',
            field=models.ForeignKey(blank=True, db_column='new_case_client_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Case Management Client Assessment'),
        ),
        migrations.AddField(
            model_name='homesafetyassessmentquestionanswers',
            name='NewCaseClientAssessment',
            field=models.ForeignKey(db_column='new_client_assessment', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Case Client Assessment'),
        ),
    ]
