# Generated by Django 3.2 on 2021-10-06 01:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('communityparamedic', '0004_auto_20211005_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVitalSigns',
            fields=[
                ('vital_signs_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bp_value', models.TextField(blank=True, null=True)),
                ('pulse_value', models.TextField(blank=True, null=True)),
                ('hr_value', models.TextField(blank=True, null=True)),
                ('rr_value', models.TextField(blank=True, null=True)),
                ('temp_value', models.TextField(blank=True, null=True)),
                ('weight_value', models.TextField(blank=True, null=True)),
                ('oximetry_choice', models.TextField(blank=True, null=True)),
                ('oximetry_value', models.TextField(blank=True, null=True)),
                ('last_weight', models.TextField(blank=True, null=True)),
                ('last_weight_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingCaseClientAssessmentChangeInCondition',
            fields=[
                ('change_in_condition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mental_status_changes', models.TextField()),
                ('functional_status_changes', models.TextField()),
                ('respiratory_changes', models.TextField()),
                ('gi_abdomen_changes', models.TextField()),
                ('gu_urine_changes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_change_in_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_changes_perceived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_condition_better_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_condition_occurred_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_condition_worse_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_other_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_treatment_last_episode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='interventions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='interventions_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='priority_problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='priority_problems_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='recommendations_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='reported_provider_name',
            field=models.ForeignKey(db_column='reported_provider', default=None, on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='Provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='risks_changes_reported_to_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='interventions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='interventions_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='priority_problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='priority_problems_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='recommendations_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='reported_provider_name',
            field=models.ForeignKey(db_column='reported_provider', default=None, on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='Provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='risks_changes_reported_to_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='community_paramedic',
            field=models.ForeignKey(blank=True, db_column='community_paramedic', null=True, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.communityparamedicuser', verbose_name='Community Paramedic'),
        ),
        migrations.AlterField(
            model_name='homesafetyassessmentquestionanswers',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='changes_in_condition',
            field=models.ForeignKey(db_column='condition_changes', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.existingcaseclientassessmentchangeincondition', verbose_name='Changes in Condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='vital_signs',
            field=models.ForeignKey(db_column='vital_signs', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.clientvitalsigns', verbose_name='Vital Signs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newcaseclientassessment',
            name='vital_signs',
            field=models.ForeignKey(db_column='vital_signs', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.clientvitalsigns', verbose_name='Vital Signs'),
            preserve_default=False,
        ),
    ]
