# Generated by Django 3.2 on 2021-10-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0005_auto_20211006_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingcaseclientassessment',
            name='assessment_change_in_condition_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingcaseclientassessmentchangeincondition',
            name='gi_abdomen_changes_detail',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existingcaseclientassessment',
            name='assessment_change_in_condition',
            field=models.BooleanField(default=False),
        ),
    ]
