# Generated by Django 3.2 on 2021-10-24 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0006_auto_20211006_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSafetyAssessment',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('answer', models.IntegerField(default=False)),
                ('answer_detail', models.TextField(blank=True, null=True)),
                ('new_client_assessment', models.ForeignKey(db_column='new_client_assessment', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Case Client Assessment')),
            ],
        ),
        migrations.RemoveField(
            model_name='homesafetyassessmentquestions',
            name='question_group',
        ),
        migrations.DeleteModel(
            name='HomeSafetyAssessmentQuestionAnswers',
        ),
        migrations.DeleteModel(
            name='HomeSafetyAssessmentQuestionGroup',
        ),
        migrations.DeleteModel(
            name='HomeSafetyAssessmentQuestions',
        ),
    ]
