# Generated by Django 3.2 on 2021-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0007_auto_20211024_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingcaseclientassessmentchangeincondition',
            name='gi_abdomen_changes_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
