version: '3.8'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - db-net


  redis:
    image: redis:4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=providertool
      - POSTGRES_USER=providertool-admin
      - POSTGRES_PASSWORD=provider-tool
    networks:
      - db-net

  frontend:
    restart: always
    command: nodemon
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web
    networks:
      - db-net
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:

networks:
  db-net:
    driver: bridge