# Generated by Django 3.2 on 2021-11-16 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TYPE_CLIENT', 'CLIENT'), ('TYPE_CLINICIAN', 'CLINICIAN'), ('TYPE_REVIEW_BOARD', 'REVIEW BOARD'), ('TYPE_COMMUNITY_PARAMEDIC', 'COMMUNITY PARAMEDIC'), ('TYPE_CASE_MANAGER', 'CASE MANAGER'), ('TYPE_ADMIN', 'ADMIN'), ('TYPE_NORMAL_USER', 'NORMAL USER')], default='TYPE_NORMAL_USER', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
