# Generated by Django 3.2 on 2022-02-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_user_type'),
        ('externalcasemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcmclientintervention',
            name='external_comm_external_followup_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externalcm_external_followup_user', to='authentication.applicationuser', verbose_name='External Follow Up User'),
        ),
        migrations.AlterField(
            model_name='externalcmclientintervention',
            name='external_comm_external_referral_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externalcm_external_referral_user', to='authentication.applicationuser', verbose_name='External Follow Up User'),
        ),
    ]
