# Generated by Django 3.2 on 2022-02-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcasemanager', '0002_auto_20220210_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalcmclientintervention',
            old_name='client_assessment_id',
            new_name='intervention_id',
        ),
    ]
