# Generated by Django 3.2 on 2022-02-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcasemanager', '0004_rename_assessment_date_externalcmclientintervention_intervention_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcmclientintervention',
            name='external_comm_external_followup_organization',
        ),
        migrations.RemoveField(
            model_name='externalcmclientintervention',
            name='external_comm_external_followup_user',
        ),
        migrations.RemoveField(
            model_name='externalcmclientintervention',
            name='external_comm_external_referral_organization',
        ),
        migrations.RemoveField(
            model_name='externalcmclientintervention',
            name='external_comm_external_referral_user',
        ),
    ]
