# Generated by Django 3.2 on 2022-02-20 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_alter_user_user_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharerCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('communication_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('communication_type', models.CharField(choices=[('0', 'Dashboard'), ('1', 'Email'), ('2', 'Fax'), ('3', 'In Person'), ('4', 'Telephone'), ('5', 'Text Message'), ('6', 'Video Conference'), ('7', 'Other')], default='0', max_length=50)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('communication_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_by', to='authentication.applicationuser', verbose_name='Communication By')),
                ('communication_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_to', to='authentication.applicationuser', verbose_name='Communication To')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_communication', to='contenttypes.contenttype')),
            ],
        ),
    ]
