# Generated by Django 3.2 on 2022-02-25 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220225_0330'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sharer', '0003_alter_sharercommunication_communication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNotifications',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_object_object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_action_object', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelManagers(
            name='sharercommunication',
            managers=[
                ('followups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNotificationsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_read', to='authentication.applicationuser')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharer.activitynotifications')),
            ],
        ),
    ]
