# Generated by Django 3.2 on 2022-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0004_auto_20220225_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynotifications',
            name='notification_type',
            field=models.CharField(choices=[('0', 'CREATED'), ('1', 'EDITED'), ('2', 'DELETED'), ('3', 'REFERRED'), ('4', 'FOLLOW_UP')], default='0', max_length=50),
        ),
    ]
