# Generated by Django 3.2 on 2022-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220225_0330'),
        ('sharer', '0005_activitynotifications_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynotifications',
            name='notification_sent_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='notification_by', to='authentication.applicationuser', verbose_name='Notification By'),
            preserve_default=False,
        ),
    ]
