# Generated by Django 3.2 on 2022-03-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0006_activitynotifications_notification_sent_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activitynotificationsread',
            constraint=models.UniqueConstraint(fields=('notification_id', 'application_user'), name='Notification-AppUser-Constraint'),
        ),
    ]
