# Generated by Django 3.2 on 2021-10-26 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagerUsers',
            fields=[
                ('casemanager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Case Manager',
                'verbose_name_plural': 'Case Managers',
            },
        ),
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_status', models.CharField(blank=True, choices=[('NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('NEW_CASE_CLIENT_EXISTING_EMC_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_CASE_CLIENT_NEW_EXTRA_MURAL_CLIENT', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], default='NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', max_length=100)),
            ],
            options={
                'verbose_name': 'Client Assessment',
                'verbose_name_plural': 'Client Assessments',
            },
        ),
        migrations.CreateModel(
            name='ClientReAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExistingEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkLoad',
            fields=[
                ('daily_workload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('daily_workload_date', models.DateField(blank=True, null=True)),
                ('client_caseload_casemanagement_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_casemanagement_total_time', models.TimeField(blank=True)),
                ('client_caseload_regular_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_regular_total_time', models.TimeField(blank=True)),
                ('project_case_management_total_time', models.TimeField(blank=True)),
                ('project_case_management_admin_total_time', models.TimeField(blank=True)),
                ('project_case_management_admin_other', models.TextField(blank=True)),
                ('research_related_meetings_total_time', models.TimeField(blank=True)),
                ('research_related_administration_total_time', models.TimeField(blank=True)),
                ('research_related_other', models.TextField(blank=True)),
                ('service_recipient_travel', models.TimeField(blank=True)),
                ('functional_center', models.TimeField(blank=True)),
                ('casemanager', models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanagerusers', verbose_name='Case Manager')),
            ],
            options={
                'verbose_name': 'Daily Workload',
                'verbose_name_plural': 'Daily Workloads',
            },
        ),
        migrations.CreateModel(
            name='ClientIntervention',
            fields=[
                ('intervention_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_clinical_intervention', models.TextField(blank=True, null=True)),
                ('clinical_type', models.TextField(blank=True, null=True)),
                ('clinical_type_detail', models.TextField(blank=True, null=True)),
                ('therapeutic_type', models.TextField(blank=True, null=True)),
                ('therapeutic_type_detail', models.TextField(blank=True, null=True)),
                ('casemanager', models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanagerusers', verbose_name='Case Manager')),
            ],
        ),
    ]
