# Generated by Django 3.2 on 2021-09-30 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientpatient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagerDailyWorkLoad',
            fields=[
                ('daily_workload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('daily_workload_date', models.DateTimeField(blank=True, null=True)),
                ('client_caseload_casemanagement_number_clients', models.IntegerField(null=True)),
                ('client_caseload_casemanagement_total_time', models.TimeField()),
                ('client_caseload_regular_number_clients', models.IntegerField(null=True)),
                ('client_caseload_regular_total_time', models.TimeField()),
                ('project_case_management_total_time', models.TimeField()),
                ('project_case_management_admin_total_time', models.TimeField()),
                ('project_case_management_admin_other', models.TextField()),
                ('research_related_meetings_total_time', models.TimeField()),
                ('research_related_administration_total_time', models.TimeField()),
                ('research_related_other', models.TextField()),
                ('service_recipient_travel', models.TimeField()),
                ('functional_center', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientReAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExistingEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientIntervention',
            fields=[
                ('intervention_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_intervention', models.TextField()),
                ('clinical_type', models.TextField()),
                ('therapeutic_type', models.TextField()),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Intervention Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_status', models.CharField(choices=[('EXISTING_ASSESS', 'Freshman'), ('EXISTING_NO_ASSESS', 'Sophomore'), ('NEW_EXTRA_MURAL', 'Junior')], default='EXISTING_ASSESS', max_length=20)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Assessment Client')),
                ('existing_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='casemanager.existingemcassessment', verbose_name='Client Assessment')),
            ],
        ),
    ]
