# Generated by Django 3.2 on 2021-10-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('casemanager', '0001_initial'),
        ('clientpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintervention',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Intervention Client'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanagerusers', verbose_name='Case Manager'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Assessment Client'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='existing_assessment',
            field=models.ForeignKey(blank=True, db_column='existing_emp_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='casemanager.existingemcassessment', verbose_name='Existing Extra Mural Client Assessment'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='newextramuralclient_assessment',
            field=models.ForeignKey(blank=True, db_column='new_extra_muralclient_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='casemanager.newemcassessment', verbose_name='New Extra-Mural Client Assessment'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='reassessment',
            field=models.ForeignKey(blank=True, db_column='client_reassessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientreassessment', verbose_name='Client Reassessment'),
        ),
        migrations.AddField(
            model_name='casemanagerusers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Case Manager'),
        ),
    ]
