# Generated by Django 3.2 on 2022-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintervention',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='total_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
