# Generated by Django 3.2 on 2021-11-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagerusers',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='casemanager', to=settings.AUTH_USER_MODEL, verbose_name='User - Case Manager'),
        ),
    ]
