# Generated by Django 3.2 on 2021-09-30 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('casemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('casemanager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Case Manager')),
            ],
            options={
                'verbose_name': 'Case Manager',
                'verbose_name_plural': 'Case Managers',
            },
        ),
        migrations.AddField(
            model_name='casemanagerdailyworkload',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', default=None, on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanager', verbose_name='Case Manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', default=None, on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanager', verbose_name='Case Manager'),
            preserve_default=False,
        ),
    ]
