# Generated by Django 3.2 on 2021-11-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0002_alter_casemanagerusers_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemanagerusers',
            old_name='user_id',
            new_name='user',
        ),
    ]
