# Generated by Django 3.2 on 2021-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0002_auto_20210930_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassessment',
            name='client_status',
            field=models.CharField(choices=[('EXISTING_ASSESS', 'Existing Extra-Mural Client Assessment'), ('EXISTING_NO_ASSESS', 'Existing Extra-Mural Client No Assessment'), ('NEW_EXTRA_MURAL', 'New Extra-Mural Client Assessment')], default='EXISTING_ASSESS', max_length=20),
        ),
    ]
