# Generated by Django 3.2 on 2021-11-26 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casemanager', '0003_rename_user_id_casemanagerusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagerusers',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='casemanager', to=settings.AUTH_USER_MODEL, verbose_name='User - Case Manager'),
        ),
    ]
