# Generated by Django 3.2 on 2021-09-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0003_alter_clientassessment_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassessment',
            name='newextramuralclient_assessment',
            field=models.ForeignKey(blank=True, db_column='newextramuralclient_assessment', default=None, on_delete=django.db.models.deletion.PROTECT, to='casemanager.newemcassessment', verbose_name='New Extra-Mural Client Assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='reassessment',
            field=models.ForeignKey(blank=True, db_column='reassessment', default=None, on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientreassessment', verbose_name='Client Reassessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientassessment',
            name='existing_assessment',
            field=models.ForeignKey(blank=True, db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='casemanager.existingemcassessment', verbose_name='Client Assessment'),
        ),
    ]
