# Generated by Django 3.2 on 2022-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0003_alter_clientintervention_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintervention',
            name='clinical_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='mode_of_clinical_intervention',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='therapeutic_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
