# Generated by Django 3.2 on 2021-11-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0012_alter_clinicalinformation_completion_date'),
        ('documents', '0002_initial'),
        ('core', '0001_initial'),
        ('casemanager', '0004_auto_20211106_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAssessment',
            new_name='CaseManagerClientAssessment',
        ),
    ]
