# Generated by Django 3.2 on 2021-10-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0004_auto_20210930_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseManagerDailyWorkLoad',
            new_name='DailyWorkLoad',
        ),
    ]
