# Generated by Django 3.2 on 2022-02-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_applicationuser'),
        ('casemanager', '0004_auto_20220129_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkload',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, to='authentication.applicationuser', verbose_name='Case Manager'),
        ),
    ]
