# Generated by Django 3.2 on 2021-10-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('casemanager', '0005_rename_casemanagerdailyworkload_dailyworkload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseManager',
            new_name='CaseManagerUsers',
        ),
    ]
