# Generated by Django 3.2 on 2022-02-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('casemanager', '0005_alter_dailyworkload_casemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintervention',
            name='casemanager',
            field=models.ForeignKey(db_column='client_intervention_casemanager', on_delete=django.db.models.deletion.PROTECT, related_name='clientintervention_casemanager', to='authentication.applicationuser', verbose_name='Client Intervention Case Manager'),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='authentication.applicationuser', verbose_name='Intervention Client'),
        ),
    ]
