# Generated by Django 3.2 on 2021-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0005_auto_20211205_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkload',
            name='research_related_other',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
