# Generated by Django 3.2 on 2022-02-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clientpatient', '0007_alter_clinicalinformation_completion_date'),
        ('casemanager', '0006_auto_20220201_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, related_name='clientassessment_casemanager', to='casemanager.casemanagerusers', verbose_name='Case Manager'),
        ),
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='clientassessment_client', to='clientpatient.client', verbose_name='Assessment Client'),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='clientintervention_client', to='authentication.applicationuser', verbose_name='Intervention Client'),
        ),
    ]
