# Generated by Django 3.2 on 2021-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0006_rename_casemanager_casemanagerusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyworkload',
            options={'verbose_name': 'Daily Workload', 'verbose_name_plural': 'Daily Workloads'},
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='daily_workload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
