# Generated by Django 3.2 on 2021-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0007_auto_20211002_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassessment',
            name='client_status',
            field=models.CharField(blank=True, choices=[('EXISTING_ASSESS', 'Existing Extra-Mural Client Assessment'), ('EXISTING_NO_ASSESS', 'Existing Extra-Mural Client No Assessment'), ('NEW_EXTRA_MURAL', 'New Extra-Mural Client Assessment')], default='EXISTING_ASSESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_casemanagement_number_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_casemanagement_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_regular_number_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_regular_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='functional_center',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='project_case_management_admin_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='project_case_management_admin_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='project_case_management_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='research_related_administration_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='research_related_meetings_total_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='research_related_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='service_recipient_travel',
            field=models.TimeField(blank=True),
        ),
    ]
