# Generated by Django 3.2 on 2022-02-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('casemanager', '0007_auto_20220201_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', on_delete=django.db.models.deletion.PROTECT, related_name='clientassessment_casemanager', to='authentication.applicationuser', verbose_name='Case Manager'),
        ),
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='clientassessment_client', to='authentication.applicationuser', verbose_name='Assessment Client'),
        ),
    ]
