# Generated by Django 3.2 on 2021-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0008_casemanagerclientassessment_assessment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemanagerclientassessment',
            name='assessment_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='assessment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
