# Generated by Django 3.2 on 2022-02-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0008_auto_20220201_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseManagerUsers',
        ),
    ]
