# Generated by Django 3.2 on 2021-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0009_auto_20211209_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagerclientassessment',
            name='client_status',
            field=models.CharField(blank=True, choices=[('NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('NEW_CASE_CLIENT_EXISTING_EMC_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_CASE_CLIENT_NEW_EXTRA_MURAL_CLIENT', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], db_column='assessment_status', default='NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', max_length=100),
        ),
    ]
