# Generated by Django 3.2 on 2021-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0010_auto_20211002_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassessment',
            name='client_status',
            field=models.CharField(blank=True, choices=[('EXISTING_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('EXISTING_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_EXTRA_MURAL', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], default='EXISTING_REASSESS', max_length=100),
        ),
    ]
