# Generated by Django 3.2 on 2021-10-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0011_alter_clientassessment_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingemcassessment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
