# Generated by Django 3.2 on 2021-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0012_alter_existingemcassessment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientassessment',
            options={'verbose_name': 'Client Assessment', 'verbose_name_plural': 'Client Assessments'},
        ),
        migrations.AlterField(
            model_name='newemcassessment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
