# Generated by Django 3.2 on 2021-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0013_auto_20211003_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassessment',
            name='client_status',
            field=models.CharField(blank=True, choices=[('EXISTING_EMC_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('EXISTING_EMC_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_EXTRA_MURAL_CLIENT', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], default='EXISTING_EMC_NO_REASSESS', max_length=100),
        ),
    ]
