# Generated by Django 3.2 on 2021-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0014_alter_clientassessment_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreassessment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
