# Generated by Django 3.2 on 2021-10-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0016_alter_clientassessment_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintervention',
            name='casemanager',
            field=models.ForeignKey(db_column='casemanager', default=None, on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanagerusers', verbose_name='Case Manager'),
            preserve_default=False,
        ),
    ]
