# Generated by Django 3.2 on 2021-10-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0017_clientintervention_casemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientintervention',
            old_name='mode_of_intervention',
            new_name='mode_of_clinical_intervention',
        ),
    ]
