# Generated by Django 3.2 on 2021-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0018_rename_mode_of_intervention_clientintervention_mode_of_clinical_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintervention',
            name='clinical_type_detail',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientintervention',
            name='therapeutic_type_detail',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
