# Generated by Django 3.2 on 2021-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0019_auto_20211003_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintervention',
            name='clinical_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='clinical_type_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='mode_of_clinical_intervention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='therapeutic_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientintervention',
            name='therapeutic_type_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
