# Generated by Django 3.2 on 2021-10-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0020_auto_20211003_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientintervention',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
