# Generated by Django 3.2 on 2021-09-30 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_label', models.TextField()),
                ('type_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterventionFormsDocuments',
            fields=[
                ('intervention_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_intervention', models.ForeignKey(db_column='client_intervention', on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientintervention', verbose_name='Client Intervention')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='documents.documenttypes', verbose_name='Document Type'),
        ),
        migrations.CreateModel(
            name='AssessmentFormsDocuments',
            fields=[
                ('assessment_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientassessment', verbose_name='Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
    ]
