# Generated by Django 3.2 on 2022-01-22 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casemanager', '0001_initial'),
        ('clinician', '0001_initial'),
        ('reviewboard', '0001_initial'),
        ('communityparamedic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('path', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_label', models.TextField()),
                ('type_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='ReviewBoardReferralFormsDocuments',
            fields=[
                ('referral_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('client_referral', models.ForeignKey(db_column='client_referral', on_delete=django.db.models.deletion.PROTECT, to='reviewboard.clientreferral', verbose_name='Client Referral')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='NewClientCommunityParamedicFormsDocuments',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionFormsDocuments',
            fields=[
                ('intervention_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_intervention', models.ForeignKey(db_column='client_intervention', on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientintervention', verbose_name='Client Intervention')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='ExistingClientCommunityParamedicFormsDocuments',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.existingcaseclientassessment', verbose_name='Existing Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianAssessmentFormsDocuments',
            fields=[
                ('assessment_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assessment_type', models.TextField()),
                ('is_provider_form', models.BooleanField(default=False)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicianclientassessment', verbose_name='Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='CaseManagerAssessmentFormsDocuments',
            fields=[
                ('assessment_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assessment_type', models.TextField()),
                ('is_provider_form', models.BooleanField(default=False)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='casemanager.casemanagerclientassessment', verbose_name='Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
    ]
