# Generated by Django 3.2 on 2021-10-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casemanager', '0002_initial'),
        ('communityparamedic', '0001_initial'),
        ('documents', '0001_initial'),
        ('reviewboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewboardreferralformsdocuments',
            name='client_referral',
            field=models.ForeignKey(db_column='client_referral', on_delete=django.db.models.deletion.PROTECT, to='reviewboard.clientreferral', verbose_name='Client Referral'),
        ),
        migrations.AddField(
            model_name='reviewboardreferralformsdocuments',
            name='document',
            field=models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='newclientcommunityparamedicformsdocuments',
            name='client_assessment',
            field=models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Client Assessment'),
        ),
        migrations.AddField(
            model_name='newclientcommunityparamedicformsdocuments',
            name='document',
            field=models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='interventionformsdocuments',
            name='client_intervention',
            field=models.ForeignKey(db_column='client_intervention', on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientintervention', verbose_name='Client Intervention'),
        ),
        migrations.AddField(
            model_name='interventionformsdocuments',
            name='document',
            field=models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='existingclientcommunityparamedicformsdocuments',
            name='client_assessment',
            field=models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.existingcaseclientassessment', verbose_name='Existing Client Assessment'),
        ),
        migrations.AddField(
            model_name='existingclientcommunityparamedicformsdocuments',
            name='document',
            field=models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='documents.documenttypes', verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='assessmentformsdocuments',
            name='client_assessment',
            field=models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='casemanager.clientassessment', verbose_name='Client Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentformsdocuments',
            name='document',
            field=models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document'),
        ),
    ]
