# Generated by Django 3.2 on 2022-02-10 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('externalcasemanager', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCMInterventionFormsDocuments',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_intervention', models.ForeignKey(db_column='client_intervention', on_delete=django.db.models.deletion.PROTECT, to='externalcasemanager.externalcmclientintervention', verbose_name='External CM Intervention')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
    ]
