# Generated by Django 3.2 on 2021-11-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_documents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewboardreferralformsdocuments',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
