# Generated by Django 3.2 on 2021-11-06 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('casemanager', '0005_rename_clientassessment_casemanagerclientassessment'),
        ('clinician', '0004_auto_20211106_2213'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentFormsDocuments',
            new_name='CaseManagerAssessmentFormsDocuments',
        ),
        migrations.CreateModel(
            name='ClinicianAssessmentFormsDocuments',
            fields=[
                ('assessment_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_provider_form', models.BooleanField(default=False)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicianclientassessment', verbose_name='Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
    ]
