# Generated by Django 3.2 on 2021-09-30 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0001_initial'),
        ('documents', '0003_auto_20210930_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityParamedicFormsDocuments',
            fields=[
                ('assessment_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_referral', models.ForeignKey(db_column='client_referral', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newclientassessment', verbose_name='Client Referral')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
    ]
