# Generated by Django 3.2 on 2021-11-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20211106_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemanagerassessmentformsdocuments',
            name='assessment_type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicianassessmentformsdocuments',
            name='assessment_type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
