# Generated by Django 3.2 on 2021-10-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_assessmentformsdocuments_is_provider_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AddField(
            model_name='documents',
            name='path',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
