# Generated by Django 3.2 on 2021-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20211002_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
