# Generated by Django 3.2 on 2021-10-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0002_auto_20211005_1019'),
        ('documents', '0007_alter_documents_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferralFormsDocuments',
            new_name='ReviewBoardReferralFormsDocuments',
        ),
    ]
