# Generated by Django 3.2 on 2021-10-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0003_auto_20211005_2334'),
        ('documents', '0008_rename_referralformsdocuments_reviewboardreferralformsdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityparamedicformsdocuments',
            name='client_referral',
        ),
        migrations.AddField(
            model_name='communityparamedicformsdocuments',
            name='client_assessment',
            field=models.ForeignKey(db_column='client_assessment', default=None, on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='Client Assessment'),
            preserve_default=False,
        ),
    ]
