# Generated by Django 3.2 on 2021-10-06 01:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communityparamedic', '0005_auto_20211006_0115'),
        ('documents', '0009_auto_20211005_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingClientCommunityParamedicFormsDocuments',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.existingcaseclientassessment', verbose_name='Existing Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='NewClientCommunityParamedicFormsDocuments',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_assessment', models.ForeignKey(db_column='client_assessment', on_delete=django.db.models.deletion.PROTECT, to='communityparamedic.newcaseclientassessment', verbose_name='New Client Assessment')),
                ('document', models.ForeignKey(db_column='document', on_delete=django.db.models.deletion.PROTECT, to='documents.documents', verbose_name='Document')),
            ],
        ),
        migrations.DeleteModel(
            name='CommunityParamedicFormsDocuments',
        ),
    ]
