# Generated by Django 3.2 on 2021-12-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211120_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TYPE_CLIENT', 'CLIENT'), ('TYPE_CLINICIAN', 'CLINICIAN'), ('TYPE_REVIEW_BOARD', 'REVIEW BOARD'), ('TYPE_COMMUNITY_PARAMEDIC', 'COMMUNITY PARAMEDIC'), ('TYPE_CASE_MANAGER', 'CASE MANAGER'), ('TYPE_ADMIN', 'ADMIN'), ('TYPE_NORMAL_USER', 'NORMAL USER')], default='TYPE_NORMAL_USER', max_length=100, null=True),
        ),
    ]
