# Generated by Django 3.2 on 2022-02-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_applicationuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='client_status',
            field=models.CharField(blank=True, choices=[('ACTIVE_CLIENT', 'Active Client'), ('DISCHARGED_CLIENT', 'Discharged Client'), ('POTENTIAL_CLIENT', 'Potential Client')], default='POTENTIAL_CLIENT', max_length=100, null=True),
        ),
    ]
