# Generated by Django 3.2 on 2022-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='organization',
            field=models.CharField(blank=True, choices=[('ORGANIZATION_ABILITY_NB', 'Ability NB'), ('ORGANIZATION_AMBULATORY_CLINIC', 'Ambulatory Clinic (Outpatient)'), ('ORGANIZATION_AMBULANCE_NEW_BRUNSWICK', 'Ambulance New Brunswick (ANB)'), ('ORGANIZATION_COMMUNITY_HEALTH_CENTERS', 'Community Health Centers'), ('ORGANIZATION_DEPARTMENT_OF_VETERAN_AFFAIRS', 'Department of Veteran Affairs'), ('ORGANIZATION_EMERGENCY_DEPARTMENT', 'Emergency Department'), ('ORGANIZATION_EXTRA_MURAL_PROGRAM', 'Extra-Mural Program'), ('ORGANIZATION_FAMILY_PHYSICIAN_OUTSIDE_COMMUNITY_HEALTH_CENTERS', 'Family Physician (Outside Community Health Centers)'), ('ORGANIZATION_FIRST_NATIONS', 'First Nations'), ('ORGANIZATION_HOMECARE_AGENCY', 'Homecare Agency'), ('ORGANIZATION_HOSPITAL_INPATIENT', 'Hospital (Inpatient)'), ('ORGANIZATION_NURSING_HOME', 'Nursing Home'), ('ORGANIZATION_PUBLIC_HEALTH_SERVICES', 'Public Health Services'), ('ORGANIZATION_RESIDENTIAL_FACILITY', 'Residential Facility'), ('ORGANIZATION_SOCIAL_DEVELOPMENT', 'Social Development'), ('ORGANIZATION_OTHER', 'Other')], default='ORGANIZATION_OTHER', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('PROVIDER_TYPE_ADMINISTRATION', 'DEFAULT'), ('PROVIDER_TYPE_DEFAULT', 'DEFAULT'), ('PROVIDER_TYPE_NUTRITIONIST', 'NUTRITIONIST'), ('PROVIDER_TYPE_OCCUPATIONAL_THERAPIST', 'OCCUPATIONAL THERAPIST'), ('PROVIDER_TYPE_PHYSICAL_THERAPIST', 'PHYSICAL THERAPIST'), ('PROVIDER_TYPE_REGISTERED_NURSE', 'REGISTERED NURSE'), ('PROVIDER_TYPE_LICENSED_PRACTICAL_NURSE', 'LICENSED PRACTICAL NURSE'), ('PROVIDER_TYPE_RESPIRATORY_THERAPIST', 'RESPIRATORY THERAPIST'), ('PROVIDER_TYPE_SOCIAL_WORKER', 'SOCIAL WORKER'), ('PROVIDER_TYPE_SPEECH_LANGUAGE_THERAPIST', 'SPEECH LANGUAGE THERAPIST')], default='PROVIDER_TYPE_DEFAULT', max_length=100, null=True),
        ),
    ]
