# Generated by Django 3.2 on 2021-09-10 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('attribute_group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_default_group', models.BooleanField(default=False)),
                ('attribute_group_code', models.CharField(max_length=55, unique=True)),
                ('attribute_group_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Field Group',
                'verbose_name_plural': 'Field Groups',
            },
        ),
        migrations.CreateModel(
            name='AttributeSet',
            fields=[
                ('attribute_set_id', models.UUIDField(db_column='attribute_set_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attribute_set_name', models.TextField()),
                ('attribute_set_code', models.CharField(db_index=True, max_length=55, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Field Set',
                'verbose_name_plural': 'Field Sets',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('entity_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type_label', models.CharField(max_length=45)),
                ('entity_type_code', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_code', models.CharField(max_length=55, unique=True)),
                ('role_label', models.TextField()),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('user_entity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleAttribute',
            fields=[
                ('attribute_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attribute_code', models.CharField(max_length=55, unique=True)),
                ('frontend_label', models.TextField()),
                ('frontend_input', models.TextField()),
                ('attribute_type', models.TextField()),
                ('is_required', models.BooleanField()),
                ('note', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('attribute_group', models.ForeignKey(db_column='attribute_group', on_delete=django.db.models.deletion.CASCADE, to='entities.attributegroup', verbose_name='Attribute Group')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='entities.roles', verbose_name='Role ID')),
                ('user_entity_id', models.ForeignKey(db_column='user_entity_id', on_delete=django.db.models.deletion.PROTECT, to='entities.userentity', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'User - Role',
                'verbose_name_plural': 'User - Roles',
            },
        ),
        migrations.CreateModel(
            name='UserRoleEntityDataTypes',
            fields=[
                ('entity_data_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_type_code', models.CharField(max_length=55, unique=True)),
                ('data_type_label', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('attribute_set_id', models.ForeignKey(db_column='attribute_set_id', on_delete=django.db.models.deletion.PROTECT, to='entities.attributeset', verbose_name='Attribute Set')),
            ],
            options={
                'verbose_name': 'User Section',
                'verbose_name_plural': 'User Sections',
            },
        ),
        migrations.CreateModel(
            name='UserRoleEntityData',
            fields=[
                ('entity_data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('entity_data_type_id', models.ForeignKey(db_column='entity_data_type_id', on_delete=django.db.models.deletion.CASCADE, to='entities.userroleentitydatatypes', verbose_name='role entity data type.')),
                ('user_entity_id', models.ForeignKey(db_column='user_entity_id', on_delete=django.db.models.deletion.CASCADE, to='entities.userentity', verbose_name='User entity id')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleAttributeValues',
            fields=[
                ('value_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(db_column='attribute', on_delete=django.db.models.deletion.PROTECT, to='entities.userroleattribute', verbose_name='role entity attribute')),
                ('entity_data', models.ForeignKey(db_column='entity_data', on_delete=django.db.models.deletion.PROTECT, to='entities.userroleentitydata', verbose_name='role entity data')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation_type', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], default='CREATE', max_length=10, verbose_name='Operation')),
                ('resource', models.ForeignKey(db_column='resource', on_delete=django.db.models.deletion.PROTECT, to='entities.userroleentitydatatypes', verbose_name='Section')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='entities.roles', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role - Permission',
                'verbose_name_plural': 'Role - Permissions',
            },
        ),
        migrations.CreateModel(
            name='EntityUpdates',
            fields=[
                ('entity_update_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_id', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField()),
                ('update_comments', models.TextField()),
                ('updated_user_id', models.CharField(max_length=32)),
                ('fields_updated', models.TextField()),
                ('entity_type_id', models.ForeignKey(db_column='entity_type_id', on_delete=django.db.models.deletion.PROTECT, to='entities.entitytype', verbose_name='Entity type')),
            ],
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='attribute_set_id',
            field=models.ForeignKey(db_column='attribute_set_id', on_delete=django.db.models.deletion.PROTECT, to='entities.attributeset', verbose_name='Attribute Set'),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='parent_attribute_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.attributegroup'),
        ),
        migrations.AddConstraint(
            model_name='rolepermissions',
            constraint=models.UniqueConstraint(fields=('role_id', 'operation_type', 'resource'), name='Unique Permission Group for: Role,Operation type and Resource'),
        ),
    ]
