# Generated by Django 3.2 on 2021-08-24 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroleentitydata',
            old_name='entity_id',
            new_name='entity_data_id',
        ),
        migrations.AddField(
            model_name='userroleentitydata',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userroleentitydata',
            name='entity_data_type_id',
            field=models.ForeignKey(db_column='entity_data_type_id', on_delete=django.db.models.deletion.CASCADE, to='entities.userroleentitydatatypes', verbose_name='role entity data type.'),
        ),
    ]
