# Generated by Django 3.2 on 2021-08-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolepermissions',
            constraint=models.UniqueConstraint(fields=('role_id', 'operation_type', 'resource_entity_id'), name='Unique Permission Group - Role,Operation type,resource entity id'),
        ),
    ]
