# Generated by Django 3.2 on 2021-08-07 20:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributeset',
            name='attribute_set_id',
            field=models.UUIDField(db_column='attribute_set_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
