# Generated by Django 3.2 on 2021-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210824_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroleattributevalues',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='userroleattributevalues',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='userroleattributevalues',
            name='entity_type_id',
        ),
        migrations.AddField(
            model_name='userroleattributevalues',
            name='attribute',
            field=models.ForeignKey(db_column='attribute', default=None, on_delete=django.db.models.deletion.PROTECT, to='entities.userroleattribute', verbose_name='role entity attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userroleattributevalues',
            name='entity_data',
            field=models.ForeignKey(db_column='entity_data', default=None, on_delete=django.db.models.deletion.PROTECT, to='entities.userroleentitydata', verbose_name='role entity data'),
            preserve_default=False,
        ),
    ]
