# Generated by Django 3.2 on 2021-08-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rolepermissions_unique permission group - role,operation type,resource entity id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='resource_entity_id',
            new_name='resource_id',
        ),
    ]
