# Generated by Django 3.2 on 2021-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210915_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalues',
            options={'verbose_name': 'Field Value', 'verbose_name_plural': 'Field Values'},
        ),
        migrations.AlterModelOptions(
            name='userentity',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userroleentitydata',
            options={'verbose_name': 'User Section Data', 'verbose_name_plural': 'User Section Data'},
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_decimal',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_time',
            field=models.TimeField(null=True),
        ),
    ]
