# Generated by Django 3.2 on 2021-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210807_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='is_default_group',
            field=models.BooleanField(default=False),
        ),
    ]
