# Generated by Django 3.2 on 2021-09-16 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20210915_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_date',
            field=models.DateField(default=datetime.date(2021, 9, 16), null=True),
        ),
    ]
