# Generated by Django 3.2 on 2021-08-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_attributegroup_is_default_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='attribute_set_id',
        ),
    ]
