# Generated by Django 3.2 on 2021-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_attributevalues_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_date',
            field=models.DateField(null=True),
        ),
    ]
