# Generated by Django 3.2 on 2021-08-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_userroleattribute_attribute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroleattribute',
            name='attribute_group',
            field=models.ForeignKey(db_column='attribute_group', default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.attributegroup', verbose_name='Attribute Group'),
            preserve_default=False,
        ),
    ]
