# Generated by Django 3.2 on 2021-09-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_attributevalues_value_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleAttributeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.TextField()),
                ('option_code', models.TextField()),
                ('attribute', models.ForeignKey(db_column='attribute', on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattribute', verbose_name='Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attributevalues',
            name='value_option',
            field=models.ForeignKey(db_column='value_option', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattributeoptions', verbose_name='option value'),
        ),
    ]
