# Generated by Django 3.2 on 2021-09-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20210917_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroleattributeoptions',
            options={'verbose_name': 'Field Option', 'verbose_name_plural': 'Field Options'},
        ),
        migrations.AlterField(
            model_name='userroleattribute',
            name='attribute_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
