# Generated by Django 3.2 on 2021-09-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20210917_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroleattribute',
            name='attribute_code',
            field=models.TextField(),
        ),
    ]
