# Generated by Django 3.2 on 2021-09-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_userroleattribute_attribute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='conditional_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userroleattribute',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
