# Generated by Django 3.2 on 2021-09-22 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20210922_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroleattributeoptions',
            options={'verbose_name': 'Field Option Value', 'verbose_name_plural': 'Field Option Values'},
        ),
        migrations.RemoveField(
            model_name='userroleattributeoptions',
            name='attribute',
        ),
        migrations.AddField(
            model_name='userroleattributeoptions',
            name='conditional_display',
            field=models.ForeignKey(db_column='conditional_display', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.attributegroup', verbose_name='Attribute group'),
        ),
        migrations.AlterField(
            model_name='attributevalues',
            name='value_option',
            field=models.ForeignKey(db_column='value_option_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattributeoptions', verbose_name='option value group'),
        ),
        migrations.CreateModel(
            name='UserRoleAttributeOptionGroup',
            fields=[
                ('group_id', models.UUIDField(db_column='option_group_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attribute', models.ForeignKey(db_column='attribute', on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattribute', verbose_name='Attribute')),
            ],
            options={
                'verbose_name': 'Field Option Group',
                'verbose_name_plural': 'Field Option Groups',
            },
        ),
        migrations.AddField(
            model_name='userroleattributeoptions',
            name='option_group',
            field=models.ForeignKey(db_column='option_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattributeoptiongroup', verbose_name='option group'),
        ),
    ]
