# Generated by Django 3.2 on 2021-09-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20210922_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroleattributeoptiongroup',
            name='group_label',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
