# Generated by Django 3.2 on 2021-09-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_userroleattributeoptiongroup_group_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalues',
            name='value_option',
            field=models.ForeignKey(db_column='value_option', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattributeoptions', verbose_name='option value'),
        ),
        migrations.AlterField(
            model_name='userroleattributeoptions',
            name='conditional_display',
            field=models.ForeignKey(db_column='conditional_display', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.attributegroup', verbose_name='Conditional Attribute group'),
        ),
        migrations.AlterField(
            model_name='userroleattributeoptions',
            name='option_group',
            field=models.ForeignKey(db_column='option_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.userroleattributeoptiongroup', verbose_name='Option Group'),
        ),
    ]
