# Generated by Django 3.2 on 2021-11-16 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientpatient', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicanUsers',
            fields=[
                ('clinician_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User - Clinican')),
            ],
            options={
                'verbose_name': 'Clinican',
                'verbose_name_plural': 'Clinicans',
            },
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('intervention_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_clinical_intervention', models.TextField(blank=True, null=True)),
                ('clinical_type', models.TextField(blank=True, null=True)),
                ('clinical_type_detail', models.TextField(blank=True, null=True)),
                ('therapeutic_type', models.TextField(blank=True, null=True)),
                ('therapeutic_type_detail', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Clinician Intervention Client')),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkLoad',
            fields=[
                ('daily_workload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('daily_workload_date', models.DateField(blank=True, null=True)),
                ('client_caseload_casemanagement_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_casemanagement_total_time', models.TimeField(blank=True)),
                ('client_caseload_regular_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_regular_total_time', models.TimeField(blank=True)),
                ('service_recipient_travel', models.TimeField(blank=True)),
                ('functional_center', models.TimeField(blank=True)),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
            ],
            options={
                'verbose_name': 'Daily Workload',
                'verbose_name_plural': 'Daily Workloads',
            },
        ),
        migrations.CreateModel(
            name='ClinicianClientAssessment',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_status', models.CharField(blank=True, choices=[('NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('NEW_CASE_CLIENT_EXISTING_EMC_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_CASE_CLIENT_NEW_EXTRA_MURAL_CLIENT', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], default='NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', max_length=100)),
                ('client', models.ForeignKey(db_column='clinician_client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Clinician Assessment Client')),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
                ('existing_assessment', models.ForeignKey(blank=True, db_column='existing_emp_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.existingemcassessment', verbose_name='Existing Extra Mural Client Assessment')),
                ('newextramuralclient_assessment', models.ForeignKey(blank=True, db_column='new_extra_muralclient_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.newemcassessment', verbose_name='New Extra-Mural Client Assessment')),
                ('reassessment', models.ForeignKey(blank=True, db_column='client_reassessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clientreassessment', verbose_name='Client Reassessment')),
            ],
            options={
                'verbose_name': 'Client Assessment',
                'verbose_name_plural': 'Client Assessments',
            },
        ),
    ]
