# Generated by Django 3.2 on 2021-11-03 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0012_alter_clinicalinformation_completion_date'),
        ('clinician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('intervention_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_clinical_intervention', models.TextField(blank=True, null=True)),
                ('clinical_type', models.TextField(blank=True, null=True)),
                ('clinical_type_detail', models.TextField(blank=True, null=True)),
                ('therapeutic_type', models.TextField(blank=True, null=True)),
                ('therapeutic_type_detail', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Clinician Intervention Client')),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkLoad',
            fields=[
                ('daily_workload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('daily_workload_date', models.DateField(blank=True, null=True)),
                ('client_caseload_casemanagement_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_casemanagement_total_time', models.TimeField(blank=True)),
                ('client_caseload_regular_number_clients', models.IntegerField(blank=True, null=True)),
                ('client_caseload_regular_total_time', models.TimeField(blank=True)),
                ('service_recipient_travel', models.TimeField(blank=True)),
                ('functional_center', models.TimeField(blank=True)),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
            ],
            options={
                'verbose_name': 'Daily Workload',
                'verbose_name_plural': 'Daily Workloads',
            },
        ),
    ]
