# Generated by Django 3.2 on 2021-11-03 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0012_alter_clinicalinformation_completion_date'),
        ('clinician', '0002_dailyworkload_interventions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianClientReAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianExistingEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianNewEMCAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_time', models.TimeField()),
                ('mode_of_assessment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianClientAssessment',
            fields=[
                ('client_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_status', models.CharField(blank=True, choices=[('NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', 'Existing Extra-Mural Client - No Reassessment'), ('NEW_CASE_CLIENT_EXISTING_EMC_REASSESS', 'Existing Extra-Mural Client Reassessment'), ('NEW_CASE_CLIENT_NEW_EXTRA_MURAL_CLIENT', 'New Extra-Mural Client Assessment'), ('EXISTING_CASE_CLIENT_REASSESS', 'Existing Case Management Client Reassessment')], default='NEW_CASE_CLIENT_EXISTING_EMC_NO_REASSESS', max_length=100)),
                ('client', models.ForeignKey(db_column='clinician_client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Clinician Assessment Client')),
                ('clinician', models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicanusers', verbose_name='Clinician')),
                ('existing_assessment', models.ForeignKey(blank=True, db_column='existing_emp_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicianexistingemcassessment', verbose_name='Existing Extra Mural Client Assessment')),
                ('newextramuralclient_assessment', models.ForeignKey(blank=True, db_column='new_extra_muralclient_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinician.cliniciannewemcassessment', verbose_name='New Extra-Mural Client Assessment')),
                ('reassessment', models.ForeignKey(blank=True, db_column='client_reassessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinician.clinicianclientreassessment', verbose_name='Client Reassessment')),
            ],
            options={
                'verbose_name': 'Client Assessment',
                'verbose_name_plural': 'Client Assessments',
            },
        ),
    ]
