# Generated by Django 3.2 on 2022-02-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0007_alter_clinicalinformation_completion_date'),
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clinician', '0002_clinicanusers_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='client',
            field=models.ForeignKey(db_column='clinician_client', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_client', to='clientpatient.client', verbose_name='Clinician Assessment Client'),
        ),
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='clinician',
            field=models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_clientassessment', to='authentication.applicationuser', verbose_name='Clinician'),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='clinician',
            field=models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_dailyworkload', to='authentication.applicationuser', verbose_name='Clinician'),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_intervention_client', to='clientpatient.client', verbose_name='Clinician Intervention Client'),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='clinician',
            field=models.ForeignKey(db_column='clinician', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_intervention_clinician', to='authentication.applicationuser', verbose_name='Clinician'),
        ),
        migrations.DeleteModel(
            name='ClinicanUsers',
        ),
    ]
