# Generated by Django 3.2 on 2022-02-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0007_alter_clinicalinformation_completion_date'),
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clinician', '0003_auto_20220202_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interventions',
            new_name='ClinicianInterventions',
        ),
    ]
