# Generated by Django 3.2 on 2021-11-06 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('clinician', '0003_clinicianclientassessment_clinicianclientreassessment_clinicianexistingemcassessment_cliniciannewemc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='existing_assessment',
            field=models.ForeignKey(blank=True, db_column='existing_emp_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.existingemcassessment', verbose_name='Existing Extra Mural Client Assessment'),
        ),
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='newextramuralclient_assessment',
            field=models.ForeignKey(blank=True, db_column='new_extra_muralclient_assessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.newemcassessment', verbose_name='New Extra-Mural Client Assessment'),
        ),
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='reassessment',
            field=models.ForeignKey(blank=True, db_column='client_reassessment', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clientreassessment', verbose_name='Client Reassessment'),
        ),
        migrations.DeleteModel(
            name='ClinicianClientReAssessment',
        ),
        migrations.DeleteModel(
            name='ClinicianExistingEMCAssessment',
        ),
        migrations.DeleteModel(
            name='ClinicianNewEMCAssessment',
        ),
    ]
