# Generated by Django 3.2 on 2022-02-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0007_alter_clinicalinformation_completion_date'),
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clinician', '0004_rename_interventions_clinicianinterventions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicianInterventions',
            new_name='ClinicianClientInterventions',
        ),
    ]
