# Generated by Django 3.2 on 2021-11-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinician', '0004_alter_clinicanusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicanusers',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='clinicianuser', to=settings.AUTH_USER_MODEL, verbose_name='User - Clinican'),
        ),
    ]
