# Generated by Django 3.2 on 2022-02-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clinician', '0005_rename_clinicianinterventions_clinicianclientinterventions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianclientinterventions',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_intervention_client', to='authentication.applicationuser', verbose_name='Clinician Intervention Client'),
        ),
    ]
