# Generated by Django 3.2 on 2022-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0006_alter_clinicianclientinterventions_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianclientinterventions',
            name='clinical_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicianclientinterventions',
            name='mode_of_clinical_intervention',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicianclientinterventions',
            name='therapeutic_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
