# Generated by Django 3.2 on 2022-02-03 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('clinician', '0007_auto_20220203_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianclientassessment',
            name='client',
            field=models.ForeignKey(db_column='clinician_client', on_delete=django.db.models.deletion.PROTECT, related_name='clinician_client', to='authentication.applicationuser', verbose_name='Clinician Assessment Client'),
        ),
    ]
