# Generated by Django 3.2 on 2022-02-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0008_alter_clinicianclientassessment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicianclientassessment',
            old_name='client_status',
            new_name='assessment_status',
        ),
    ]
