# Generated by Django 3.2 on 2022-02-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0009_rename_client_status_clinicianclientassessment_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_casemanagement_number_clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_casemanagement_total_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_regular_number_clients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='client_caseload_regular_total_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='daily_workload_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='functional_center',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkload',
            name='service_recipient_travel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
