# Generated by Django 3.2 on 2022-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0010_auto_20220203_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianclientassessment',
            name='assessment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicianclientassessment',
            name='assessment_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
