# Generated by Django 3.2 on 2021-12-22 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBoardUser',
            fields=[
                ('reviewboard_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviewboarduser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Board User',
                'verbose_name_plural': 'Review Board Users',
            },
        ),
        migrations.CreateModel(
            name='ClientReferral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('client_first_name', models.TextField()),
                ('client_last_name', models.TextField()),
                ('client_email', models.TextField()),
                ('referral_source', models.TextField(blank=True, null=True)),
                ('referral_source_detail', models.TextField(blank=True, null=True)),
                ('organizations_upon_referral', models.JSONField(blank=True, null=True)),
                ('organizations_upon_referral_detail', models.TextField(blank=True, null=True)),
                ('date_of_case_discussion', models.DateField(blank=True, null=True)),
                ('members_present_case_discussion', models.JSONField(blank=True, null=True)),
                ('members_present_case_discussion_detail', models.TextField(blank=True, null=True)),
                ('case_management_organization_responsible', models.TextField(blank=True, null=True)),
                ('case_management_organization_person_responsible', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('ACTIVE_CLIENT', 'Active Client'), ('DISCHARGED_CLIENT', 'Discharged Client'), ('POTENTIAL_CLIENT', 'Potential Client')], default='POTENTIAL_CLIENT', max_length=20)),
                ('decision_detail', models.TextField(blank=True, null=True)),
                ('review_board_user', models.ForeignKey(db_column='review_board_user', on_delete=django.db.models.deletion.PROTECT, to='reviewboard.reviewboarduser', verbose_name='Review Board User')),
            ],
        ),
    ]
