# Generated by Django 3.2 on 2021-09-30 04:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientpatient', '0002_client_client_active'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBoardMember',
            fields=[
                ('reviewboard_member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Review Board')),
            ],
            options={
                'verbose_name': 'Review Board User',
                'verbose_name_plural': 'Review Board Users',
            },
        ),
        migrations.CreateModel(
            name='ClientReferral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.TextField()),
                ('referral_source_detail', models.TextField()),
                ('organizations_upon_referral', models.TextField()),
                ('organizations_upon_referral_detail', models.TextField()),
                ('date_of_case_discussion', models.DateTimeField(blank=True, null=True)),
                ('members_present_case_discussion', models.TextField()),
                ('members_present_case_discussion_detail', models.TextField()),
                ('case_management_organization_responsible', models.TextField()),
                ('decision', models.CharField(choices=[('REFERRAL_ACCEPTED', 'Client Accepted'), ('REFERRAL_REFUSED', 'Client Refused')], default='REFERRAL_REFUSED', max_length=20)),
                ('decision_detail', models.TextField()),
                ('case_management_user_responsible', models.ForeignKey(db_column='case_management_user_responsible', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='Person Responsible for Client Case Management')),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Referral Client')),
            ],
        ),
    ]
