# Generated by Django 3.2 on 2022-02-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_applicationuser_client_status'),
        ('reviewboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreferral',
            name='review_board_user',
            field=models.ForeignKey(db_column='review_board_user', on_delete=django.db.models.deletion.PROTECT, to='authentication.applicationuser', verbose_name='Review Board User'),
        ),
        migrations.DeleteModel(
            name='ReviewBoardUser',
        ),
    ]
