# Generated by Django 3.2 on 2021-10-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreferral',
            old_name='case_management_user_responsible',
            new_name='case_management_organization_user_responsible',
        ),
        migrations.RemoveField(
            model_name='clientreferral',
            name='client',
        ),
        migrations.AddField(
            model_name='clientreferral',
            name='client_email',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientreferral',
            name='client_first_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientreferral',
            name='client_last_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientreferral',
            name='review_board_user',
            field=models.ForeignKey(db_column='review_board_user', default=None, on_delete=django.db.models.deletion.PROTECT, to='reviewboard.reviewboardmember', verbose_name='Review Board User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='case_management_organization_responsible',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='date_of_case_discussion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='decision',
            field=models.CharField(choices=[('ACTIVE_CLIENT', 'Active Client'), ('DISCHARGED_CLIENT', 'Discharged Client'), ('POTENTIAL_CLIENT', 'Potential Client')], default='POTENTIAL_CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='members_present_case_discussion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='members_present_case_discussion_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='organizations_upon_referral',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='organizations_upon_referral_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='referral_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='referral_source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='referral_source_detail',
            field=models.TextField(null=True),
        ),
    ]
