# Generated by Django 3.2 on 2021-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0002_alter_reviewboarduser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreferral',
            name='members_present_case_discussion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='organizations_upon_referral',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
