# Generated by Django 3.2 on 2021-10-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reviewboard', '0003_rename_reviewboardmember_reviewboarduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewboarduser',
            old_name='reviewboard_member_id',
            new_name='reviewboard_user_id',
        ),
        migrations.AlterField(
            model_name='reviewboarduser',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User'),
        ),
    ]
