# Generated by Django 3.2 on 2021-11-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0003_auto_20211114_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewboarduser',
            old_name='user_id',
            new_name='user',
        ),
    ]
