# Generated by Django 3.2 on 2021-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0004_auto_20211005_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreferral',
            name='case_management_organization_user_responsible',
        ),
        migrations.AddField(
            model_name='clientreferral',
            name='case_management_organization_person_responsible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='case_management_organization_responsible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='members_present_case_discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='members_present_case_discussion_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='organizations_upon_referral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='organizations_upon_referral_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='referral_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientreferral',
            name='referral_source_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
