# Generated by Django 3.2 on 2021-11-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewboard', '0006_alter_reviewboarduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreferral',
            name='decision_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
