# Generated by Django 3.2 on 2021-10-26 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceUse',
            fields=[
                ('ambulance_use_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ambulance_use_six_months', models.IntegerField(blank=True, null=True)),
                ('ambulance_use_medical_reason_six_months', models.TextField(blank=True, null=True)),
                ('ambulance_use_twelve_months', models.IntegerField(blank=True, null=True)),
                ('ambulance_use_medical_reason_twelve_months', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_active', models.BooleanField(default=False, verbose_name='Client Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client_status', models.CharField(blank=True, choices=[('ACTIVE_CLIENT', 'Active Client'), ('DISCHARGED_CLIENT', 'Discharged Client'), ('POTENTIAL_CLIENT', 'Potential Client')], default='POTENTIAL_CLIENT', max_length=100)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.users', verbose_name='User - Client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClinicalInformation',
            fields=[
                ('clinical_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('family_physician', models.TextField(blank=True, null=True)),
                ('nurse_practitioner', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('ambulance_use', models.ForeignKey(db_column='ambulance_use', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.ambulanceuse', verbose_name='Ambulance Use')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRoomVisits',
            fields=[
                ('emergency_room_visit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emergency_room_count_six_months', models.IntegerField(blank=True, null=True)),
                ('emergency_room_count_twelve_months', models.IntegerField(blank=True, null=True)),
                ('emergency_room_last_date', models.DateField(blank=True, null=True)),
                ('emergency_room_last_medical_reason', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSupportServices',
            fields=[
                ('home_support_services_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('informal_support', models.TextField(blank=True, null=True)),
                ('informal_support_detail', models.TextField(blank=True, null=True)),
                ('formal_support', models.TextField(blank=True, null=True)),
                ('formal_support_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('medical_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cancer', models.TextField(blank=True, null=True)),
                ('cardiac', models.TextField(blank=True, null=True)),
                ('cardiac_detail', models.TextField(blank=True, null=True)),
                ('circulatory', models.TextField(blank=True, null=True)),
                ('circulatory_detail', models.TextField(blank=True, null=True)),
                ('integumentary', models.TextField(blank=True, null=True)),
                ('integumentary_detail', models.TextField(blank=True, null=True)),
                ('endocrine', models.TextField(blank=True, null=True)),
                ('endocrine_detail', models.TextField(blank=True, null=True)),
                ('eye', models.TextField(blank=True, null=True)),
                ('eye_detail', models.TextField(blank=True, null=True)),
                ('frailty', models.TextField(blank=True, null=True)),
                ('gastro_intestinal', models.TextField(blank=True, null=True)),
                ('musculoskeletal', models.TextField(blank=True, null=True)),
                ('musculoskeletal_detail', models.TextField(blank=True, null=True)),
                ('neurological', models.TextField(blank=True, null=True)),
                ('neurological_detail', models.TextField(blank=True, null=True)),
                ('obesity', models.TextField(blank=True, null=True)),
                ('post_surgical', models.TextField(blank=True, null=True)),
                ('genital_urinary', models.TextField(blank=True, null=True)),
                ('genital_urinary_detail', models.TextField(blank=True, null=True)),
                ('respiratory', models.TextField(blank=True, null=True)),
                ('respiratory_detail', models.TextField(blank=True, null=True)),
                ('substance_abuse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousHospitalization',
            fields=[
                ('previous_hospitalization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hospitalizations_six_months', models.IntegerField(blank=True, default=0, null=True)),
                ('hospitalizations_twelve_months', models.IntegerField(blank=True, default=0, null=True)),
                ('hospitalization_last_date', models.DateField(blank=True, null=True)),
                ('hospitalization_last_stay_length', models.IntegerField(blank=True, null=True)),
                ('hospitalization_last_medical_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('visit_reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('medication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medication_name', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('intake_frequency', models.TextField(blank=True, null=True)),
                ('clinical_id', models.ForeignKey(db_column='clinical_id', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.clinicalinformation', verbose_name='Clinical Information')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('person_completing', models.TextField(blank=True, null=True)),
                ('person_completing_detail', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='emergency_room_visits',
            field=models.ForeignKey(db_column='emergency_room_visits', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.emergencyroomvisits', verbose_name='ER Visits'),
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='home_support_services',
            field=models.ForeignKey(db_column='home_support_services', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.homesupportservices', verbose_name='Home Support Services'),
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='last_hospitalization',
            field=models.ForeignKey(db_column='last_hospitalization', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.previoushospitalization', verbose_name='Last Hospitalization'),
        ),
        migrations.AddField(
            model_name='clinicalinformation',
            name='medical_diagnosis',
            field=models.ForeignKey(db_column='medical_diagnosis', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.medicaldiagnosis', verbose_name='Medical Diagnosis'),
        ),
    ]
