# Generated by Django 3.2 on 2021-10-27 00:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalinformation',
            name='client',
            field=models.ForeignKey(db_column='client', default=None, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('clinical_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ethnic_background', models.TextField(blank=True, null=True)),
                ('ethnic_background_detail', models.TextField(blank=True, null=True)),
                ('language_proficiency_english', models.TextField(blank=True, null=True)),
                ('language_proficiency_french', models.TextField(blank=True, null=True)),
                ('language_proficiency_other', models.TextField(blank=True, null=True)),
                ('language_proficiency_interpreter', models.TextField(blank=True, null=True)),
                ('marital_status', models.TextField(blank=True, null=True)),
                ('marital_status_detail', models.TextField(blank=True, null=True)),
                ('family_situation', models.TextField(blank=True, null=True)),
                ('family_situation_detail', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('education_detail', models.TextField(blank=True, null=True)),
                ('employment', models.TextField(blank=True, null=True)),
                ('employment_detail', models.TextField(blank=True, null=True)),
                ('household_income', models.TextField(blank=True, null=True)),
                ('household_income_detail', models.TextField(blank=True, null=True)),
                ('housing_situation', models.TextField(blank=True, null=True)),
                ('housing_situation_detail', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSafetyAssessment',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('answer', models.IntegerField(default=False)),
                ('answer_detail', models.TextField(blank=True, null=True)),
                ('personal_information', models.ForeignKey(db_column='personal_information', default=None, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.personalinformation', verbose_name='Personal Information')),
            ],
        ),
    ]
