# Generated by Django 3.2 on 2021-11-22 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientpatient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientuser', to='authentication.user', verbose_name='User - Client'),
            preserve_default=False,
        ),
    ]
