# Generated by Django 3.2 on 2021-10-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0002_auto_20211027_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', unique=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', unique=True, verbose_name='Client'),
        ),
    ]
