# Generated by Django 3.2 on 2021-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0002_client_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_active',
            field=models.BooleanField(default=False, verbose_name='Client Active'),
        ),
    ]
