# Generated by Django 3.2 on 2021-10-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0003_alter_client_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('ACTIVE_CLIENT', 'Active Client'), ('DISCHARGED_CLIENT', 'Discharged Client'), ('POTENTIAL_CLIENT', 'Potential Client')], default='POTENTIAL_CLIENT', max_length=100),
        ),
    ]
