# Generated by Django 3.2 on 2021-10-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0003_auto_20211027_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', unique=True, verbose_name='Client'),
        ),
    ]
