# Generated by Django 3.2 on 2021-12-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0003_auto_20211204_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='language_proficiency',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
