# Generated by Django 3.2 on 2022-01-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0004_alter_personalinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='emergency_room_last_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='hospitalization_last_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='revision_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
