# Generated by Django 3.2 on 2022-01-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0005_auto_20220125_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='ambulance_use_six_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='ambulance_use_twelve_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='emergency_room_count_six_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='emergency_room_count_twelve_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='hospitalization_last_stay_length',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='hospitalizations_six_months',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='hospitalizations_twelve_months',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
