# Generated by Django 3.2 on 2021-10-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0005_alter_visitorlog_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='client',
            field=models.OneToOneField(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='completion_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
