# Generated by Django 3.2 on 2022-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0006_auto_20220125_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='completion_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
