# Generated by Django 3.2 on 2021-10-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0006_auto_20211029_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='clinical_id',
            new_name='personal_id',
        ),
    ]
