# Generated by Django 3.2 on 2021-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0007_rename_clinical_id_personalinformation_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesafetyassessment',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homesafetyassessment',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
