# Generated by Django 3.2 on 2021-10-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0008_auto_20211029_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesafetyassessment',
            name='question_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
