# Generated by Django 3.2 on 2021-10-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0009_homesafetyassessment_question_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='ambulance_use',
            field=models.ForeignKey(blank=True, db_column='ambulance_use', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.ambulanceuse', verbose_name='Ambulance Use'),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='emergency_room_visits',
            field=models.ForeignKey(blank=True, db_column='emergency_room_visits', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.emergencyroomvisits', verbose_name='ER Visits'),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='home_support_services',
            field=models.ForeignKey(blank=True, db_column='home_support_services', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.homesupportservices', verbose_name='Home Support Services'),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='last_hospitalization',
            field=models.ForeignKey(blank=True, db_column='last_hospitalization', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.previoushospitalization', verbose_name='Last Hospitalization'),
        ),
        migrations.AlterField(
            model_name='clinicalinformation',
            name='medical_diagnosis',
            field=models.ForeignKey(blank=True, db_column='medical_diagnosis', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientpatient.medicaldiagnosis', verbose_name='Medical Diagnosis'),
        ),
        migrations.AlterField(
            model_name='emergencyroomvisits',
            name='emergency_room_last_medical_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
