# Generated by Django 3.2 on 2021-10-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0010_auto_20211030_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='client',
            field=models.OneToOneField(db_column='client', on_delete=django.db.models.deletion.PROTECT, to='clientpatient.client', verbose_name='Client'),
        ),
    ]
