# Generated by Django 3.2 on 2021-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpatient', '0011_alter_clinicalinformation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinformation',
            name='completion_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
